### ISSUE TITLE
Implementing the Runge-Kutta Fehlberg

### ISSUE THREAD

**Issue by amirh0ss3in** [pmocz/nbody-python#1]
I have implemented the Runge-Kutta Fehlberg algorithm in python, and used it to calculate Lissajous curve problem:
https://github.com/amirh0ss3in/RKF
I was wondering if it is possible for you to implement this method in your code or preferably, can we work jointly on this feature?

**Comment by pmocz** [comment]
Hi @amirh0ss3in! I'd like to encourage you to fork the code and try an implementation of Runge-Kutta Fehlberg ([RK45](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta%E2%80%93Fehlberg_method)) yourself. To give some hints, below is what an implementation of [RK4](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods#The_Runge%E2%80%93Kutta_method) may look like. Generally speaking, leapfrog integrators as opposed to RK integrators tend to do a better job an energy conservation in the N-body problem, so I prefer to use those. For a higher-order leapfrog scheme, see the [4th-order Yoshida integrator](https://en.wikipedia.org/wiki/Leapfrog_integration#4th_order_Yoshida_integrator)

```python
# Simulation Main Loop
for i in range(Nt):

	# RK4 time integrator
	k1 = dt * getAcc( pos, mass, G, softening )    # k = velocity update
	m1 = dt * vel                                  # m = position update
	
	k2 = dt * getAcc( pos + 0.5*m1, mass, G, softening )
	m2 = dt * (vel + 0.5*k1)
	
	k3 = dt * getAcc( pos + 0.5*m2, mass, G, softening )
	m3 = dt * (vel + 0.5*k2)
	
	k4 = dt * getAcc( pos + m3, mass, G, softening )
	m4 = dt * (vel + k3)
	
	vel += (k1+ 2*k2 + 2*k3 + k4)/6
	pos += (m1+ 2*m2 + 2*m3 + m4)/6

	# update time
	t += dt
```
